image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  # Define Docker image names and tags
  CONTAINER_IMAGE: registry.gitlab.com/acp-group/acp-innsbruck/ibk_demo_ai_auto_docu:$CI_COMMIT_SHA
  CONTAINER_IMAGE_LATEST: registry.gitlab.com/acp-group/acp-innsbruck/ibk_demo_ai_auto_docu:latest

stages:
  - build

before_script:
  # Log in to GitLab Container Registry
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t "$CONTAINER_IMAGE" -t "$CONTAINER_IMAGE_LATEST" .
    - docker push "$CONTAINER_IMAGE"
    - docker push "$CONTAINER_IMAGE_LATEST"



